---
- hosts: fs
  gather_facts: true
  become: true
  user: rj

  roles:
    - { role: xyzrbt.common, tags: ['common'] }
    - { role: xyzrbt.couchpotato, tags: ['cp'] }
    - { role: xyzrbt.sickrage, tags: ['sr'] }
    - { role: xyzrbt.headphones, tags: ['hp'] }
